# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "mmain" , "fe", "be", "be-*" ]
  pull_request:
    branches: [ "main", "be", "be-*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin:~/bin'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
    

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.0.0
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: x64

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: fetch dfx
        run: sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      
      - name : check version
        run : dfx --version
        
      - name : install dependencies
        run : npm install
        
        
      - name : run dfx
        run : |
          dfx start --background
          dfx deploy --argument "(
            record {
              name = \"My DIP721\";
              symbol = \"DFXB\";
              address = principal\"$(dfx identity get-principal)\"
            }
          )"
        # - name: mint NFT
        # run : dfx canister call final_be mintNFT \ "( principal\"$(dfx identity get-principal)\", opt record {desc=\"Test\"; name=\"test\"} )"


      - name : stop dfx
        run : dfx stop
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
